baseURL: 'https://timhradil.com/'
languageCode: en-us
title: My New Hugo Site
theme: hugo-alageek-theme
Title: 'Hi, I''m Tim.'
menu:
  primary:
    - identifier: chat
      name: Chat With Me
      title: Chat
      url: https://chat.timhradil.com
      weight: -140
    - identifier: resume
      name: Resume
      title: Resume
      url: /resume/
      weight: -130
    - identifier: projects
      name: Projects
      title: projects section
      url: /projects/
      weight: -120
    - identifier: blog
      name: Blog
      title: blog section
      url: /blog/
      weight: -110
    - identifier: artwork
      name: Artwork
      title: artwork section
      url: /artwork/
      weight: -100
params:
  logoURL: 'https://timhradil.com/'
  logofile: ./logo.png
  email: timhradil@gmail.com
  twiter: timhradil
  github: timhradil
  linkedin: timhradil
  faviconfile: ./logo.ico
  favorite_things: 
    - name: Book
      url: https://www.amazon.com/Hitchhikers-Guide-Galaxy-Douglas-Adams/dp/0345391802
      title: The Hitchiker's Guide to the Galaxy
    - name: Movie 
      url: https://www.imdb.com/title/tt0816692/
      title: Interstellar
    - name: Food
      url: https://handletheheat.com/lemon-poppy-seed-muffins/
      title: Lemon Poppy Seed Muffins
    - name: Text Editor
      url: https://www.vim.org/
      title: Vim
    - name: Language
      url: https://www.python.org/
      title: Python
markup:
  goldmark:
    renderer:
      unsafe: true
